"""baseline do schema do mordomo

Revision ID: 22dcfb58438e
Revises: 
Create Date: 2026-08-10 14:50:41.154357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22dcfb58438e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=80), nullable=True),
    sa.Column('turn_id', sa.String(length=32), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_events_member_id'), 'product_events', ['member_id'], unique=False)
    op.create_index(op.f('ix_product_events_session_id'), 'product_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_product_events_tipo'), 'product_events', ['tipo'], unique=False)
    op.create_index(op.f('ix_product_events_ts'), 'product_events', ['ts'], unique=False)
    op.create_index(op.f('ix_product_events_turn_id'), 'product_events', ['turn_id'], unique=False)
    op.create_table('channel_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canal', 'external_id')
    )
    op.create_table('family_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('inicio_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('local', sa.String(length=200), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('quando_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminders')
    op.drop_table('family_events')
    op.drop_table('channel_identities')
    op.drop_index(op.f('ix_product_events_turn_id'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_ts'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_tipo'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_session_id'), table_name='product_events')
    op.drop_index(op.f('ix_product_events_member_id'), table_name='product_events')
    op.drop_table('product_events')
    op.drop_table('members')
    # ### end Alembic commands ###
