"""vault_items (cofre)

Revision ID: 3817d9bcba77
Revises: 3d3f4a87f977
Create Date: 2026-08-11 12:44:36.710685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3817d9bcba77'
down_revision: Union[str, Sequence[str], None] = '3d3f4a87f977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.String(length=500), nullable=False),
    sa.Column('dono', sa.Integer(), nullable=False),
    sa.Column('compartilhado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dono'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vault_items')
    # ### end Alembic commands ###
