"""invite_codes (/vincular)

Revision ID: 9f449495dfb6
Revises: 22dcfb58438e
Create Date: 2026-08-10 21:03:34.023966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f449495dfb6'
down_revision: Union[str, Sequence[str], None] = '22dcfb58438e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=16), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_por', sa.Integer(), nullable=True),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['members.id'], ),
    sa.ForeignKeyConstraint(['usado_por'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_codes')
    # ### end Alembic commands ###
